---
# tasks file for roles/app

  - name: Create backend container and connect to network
    docker_container:
      name: backend
      image: simonghlk/tp-devops:simple-api
      networks:
        - name: app-network
      ports:
        - 8080:8080
